version: 0.2

env:
  variables:
    SDLC_ENV: "$1"
    TF_COMMAND: "$2"
    TERRAFORM_VERSION: "1.9.5"
  # Uncomment and configure if you need secrets from AWS Secrets Manager:
  # secrets-manager:
  #   TF_CLOUD_TOKEN: "TF_CLOUD_Secret:MY_SECRET_VAR"

phases:
  install:
    runtime-versions:
      python: 3.11
    on-failure: ABORT
    commands:
      - tf_version=$TERRAFORM_VERSION
      - wget https://releases.hashicorp.com/terraform/"$tf_version"/terraform_"$tf_version"_linux_amd64.zip
      - unzip -o terraform_"$tf_version"_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - terraform --version
  pre_build:
    on-failure: ABORT
    commands:
      - echo "Terraform execution started on $(date)"
  build:
    on-failure: ABORT
    commands:
      - ls -lrt "$CODEBUILD_SRC_DIR/terraform-manifests"
      - terraform --version
      - echo "Command to run: ${TF_COMMAND}"
      - echo "SDLC_ENV: ${SDLC_ENV}"
      - cd "$CODEBUILD_SRC_DIR/terraform-manifests/${SDLC_ENV}"
      - terraform init
      - terraform validate
      - terraform plan
      - terraform $TF_COMMAND -auto-approve
  post_build:
    on-failure: CONTINUE
    commands:
      - echo "Terraform execution completed on $(date)"
